# This file was generated by GoReleaser. DO NOT EDIT.
class Stripe < Formula
  desc "Stripe CLI utility"
  homepage "https://stripe.com"
  version "1.5.21"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/suz-stripe/stripe-cli/releases/download/v1.5.21/stripe_1.5.21_mac-os_x86_64.tar.gz"
    sha256 "7d4d61a078186ae4fbece609e4de32c06d189f97143ef7106439a89001ff2a45"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/suz-stripe/stripe-cli/releases/download/v1.5.21/stripe_1.5.21_linux_x86_64.tar.gz"
      sha256 "dbac49c3cb0e2609fe9e83088f608dde300936ff39999e0a09f4758f9896e0d8"
    end
  end

  def install
    bin.install "stripe"
    rm Dir["#{bin}/{stripe-completion.bash,stripe-completion.zsh}"]
    system bin/"stripe", "completion", "--shell", "bash"
    system bin/"stripe", "completion", "--shell", "zsh"
    bash_completion.install "stripe-completion.bash"
    zsh_completion.install "stripe-completion.zsh"
    (zsh_completion/"_stripe").write <<~EOS
      #compdef stripe
      _stripe () {
        local e
        e=$(dirname ${funcsourcetrace[1]%:*})/stripe-completion.zsh
        if [[ -f $e ]]; then source $e; fi
      }
    EOS
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the Stripe CLI! If this is your first time using the CLI, be sure to run `stripe login` first.
  EOS
  end
end
