# This file was generated by GoReleaser. DO NOT EDIT.
class Stripe < Formula
  desc "Stripe CLI utility"
  homepage "https://stripe.com"
  version "1.5.23"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/suz-stripe/stripe-cli/releases/download/v1.5.23/stripe_1.5.23_mac-os_x86_64.tar.gz"
    sha256 "bc59e3a8e2775a57a19ea0f172995db201782225eb72c69cfdccf813ebc3ff30"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/suz-stripe/stripe-cli/releases/download/v1.5.23/stripe_1.5.23_linux_x86_64.tar.gz"
      sha256 "0e739c8235e4c8aa993d8dce8634f799ca2e6d9798a9df5c07b1cf1e89ab22ee"
    end
  end

  def install
    bin.install "stripe"
    rm Dir["#{bin}/{stripe-completion.bash,stripe-completion.zsh}"]
    system bin/"stripe", "completion", "--shell", "bash"
    system bin/"stripe", "completion", "--shell", "zsh"
    bash_completion.install "stripe-completion.bash"
    zsh_completion.install "stripe-completion.zsh"
    (zsh_completion/"_stripe").write <<~EOS
      #compdef stripe
      _stripe () {
        local e
        e=$(dirname ${funcsourcetrace[1]%:*})/stripe-completion.zsh
        if [[ -f $e ]]; then source $e; fi
      }
    EOS
  end

  def caveats; <<~EOS
    ❤ Thanks for installing the Stripe CLI! If this is your first time using the CLI, be sure to run `stripe login` first.
  EOS
  end
end
