# This is a basic workflow to help you get started with Actions

name: brew / scoop install test

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  brew_test:
    runs-on: macos-latest
    steps:
      - name: brew tap / install 
        run: |
           brew tap suz-stripe/stripe https://github.com/suz-stripe/cli-pkg-mngr-testing
           ls -la /usr/local/Homebrew/Library/Taps/suz-stripe/homebrew-stripe
           ls -la /usr/local/Homebrew/Library/Taps/suz-stripe/homebrew-stripe/brew
           brew install /usr/local/Homebrew/Library/Taps/suz-stripe/homebrew-stripe/brew/stripe.rb
  scoop_test:
    runs-on: windows-latest
    steps:
      - name: scoop bucket / install
        run: |
           Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
           scoop install https://raw.githubusercontent.com/suz-stripe/cli-pkg-mngr-testing/master/scoop/stripe.json
        shell: pwsh
